// Renders data/calibration.ts from a plain object, and the small statistics
// scripts/calibrate.ts needs. The generated file keeps the same header, the
// same Band interface, the same exports, and every hand-entered band; only
// the computed bands change. The hand() helper of the hand-written version
// is not emitted: every band is a literal object.

import type { Band } from '../../data/calibration';

export type CalibrationTree = { [key: string]: Band | CalibrationTree };

export function isBand(x: unknown): x is Band {
  return !!x && typeof x === 'object' && 'low' in x && 'high' in x && 'typical' in x && 'verified' in x;
}

// Linear interpolation percentile, p in [0, 1].
export function percentile(values: number[], p: number): number {
  if (values.length === 0) throw new Error('percentile of an empty list');
  const sorted = [...values].sort((a, b) => a - b);
  const h = (sorted.length - 1) * Math.min(1, Math.max(0, p));
  const i = Math.floor(h);
  const a = sorted[i] ?? 0;
  const b = sorted[Math.min(i + 1, sorted.length - 1)] ?? a;
  return a + (b - a) * (h - i);
}

export function median(values: number[]): number {
  return percentile(values, 0.5);
}

// The band shape for a computed value: 5th percentile, 95th, median.
export function bandFromYearly(values: number[], unit: string, source: string, query: string, window: string, note: string): Band {
  return {
    low: round(percentile(values, 0.05)),
    high: round(percentile(values, 0.95)),
    typical: round(median(values)),
    unit,
    source,
    verified: true,
    note,
    query,
    window,
    computedOn: new Date().toISOString().slice(0, 10),
  };
}

export function round(n: number, decimals = 4): number {
  const f = 10 ** decimals;
  return Math.round(n * f) / f;
}

function str(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
}

function num(n: number): string {
  if (!Number.isFinite(n)) throw new Error(`calibration band has a non-finite number: ${n}`);
  return String(n);
}

const HEADER = `// Every calibration constant in the game lives here (CLAUDE.md rule 10).
// A band with verified: true was computed by scripts/calibrate.ts from FDIC
// data and carries the query, window, and date. A band with verified: false
// was typed by hand and says why. Tests that read an unverified band are
// tagged unverified and report separately (rule 20). Never tune a band to
// make a test pass.
//
// Generated by scripts/calibrate.ts. Edit hand-entered bands here; computed
// bands are overwritten on the next run.

export interface Band {
  low: number;
  high: number;
  typical: number;
  unit: string;
  source: string;
  verified: boolean;
  note: string;
  query?: string;
  window?: string;
  computedOn?: string;
}
`;

const FOOTER = `
export type Calibration = typeof calibration;

export function unverifiedBands(): string[] {
  const out: string[] = [];
  const walk = (node: unknown, path: string) => {
    if (node && typeof node === 'object') {
      if ('verified' in node && 'low' in node) {
        if (!(node as Band).verified) out.push(path);
        return;
      }
      for (const [k, v] of Object.entries(node)) walk(v, path ? \`\${path}.\${k}\` : k);
    }
  };
  walk(calibration, '');
  return out;
}
`;

function renderBand(b: Band, unverifiedConst: string | null): string {
  const parts = [
    `low: ${num(b.low)}`,
    `high: ${num(b.high)}`,
    `typical: ${num(b.typical)}`,
    `unit: ${str(b.unit)}`,
    `source: ${str(b.source)}`,
    `verified: ${b.verified ? 'true' : 'false'}`,
    `note: ${unverifiedConst !== null && b.note === unverifiedConst ? 'UNVERIFIED' : str(b.note)}`,
  ];
  if (b.query !== undefined) parts.push(`query: ${str(b.query)}`);
  if (b.window !== undefined) parts.push(`window: ${str(b.window)}`);
  if (b.computedOn !== undefined) parts.push(`computedOn: ${str(b.computedOn)}`);
  return `{ ${parts.join(', ')} }`;
}

function renderNode(node: CalibrationTree, indent: string, unverifiedConst: string | null, comments: Record<string, string[]>, path: string): string {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(node)) {
    const full = path ? `${path}.${key}` : key;
    for (const c of comments[full] ?? []) lines.push(`${indent}// ${c}`);
    if (isBand(value)) {
      lines.push(`${indent}${key}: ${renderBand(value, unverifiedConst)},`);
    } else {
      lines.push(`${indent}${key}: {`);
      lines.push(renderNode(value, indent + '  ', unverifiedConst, comments, full));
      lines.push(`${indent}},`);
    }
  }
  return lines.join('\n');
}

// The most common note among hand-entered bands is hoisted to a constant so
// the file stays readable; every other note is written inline.
function commonUnverifiedNote(tree: CalibrationTree): string | null {
  const counts = new Map<string, number>();
  const walk = (node: CalibrationTree) => {
    for (const v of Object.values(node)) {
      if (isBand(v)) {
        if (!v.verified) counts.set(v.note, (counts.get(v.note) ?? 0) + 1);
      } else walk(v);
    }
  };
  walk(tree);
  let best: string | null = null;
  let bestCount = 1;
  for (const [note, n] of counts) {
    if (n > bestCount) {
      best = note;
      bestCount = n;
    }
  }
  return best;
}

export function renderCalibrationFile(tree: CalibrationTree, comments: Record<string, string[]>): string {
  const unverified = commonUnverifiedNote(tree);
  const parts = [HEADER];
  if (unverified !== null) parts.push(`\nconst UNVERIFIED =\n  ${str(unverified)};\n`);
  parts.push('\nexport const calibration = {\n');
  parts.push(renderNode(tree, '  ', unverified, comments, ''));
  parts.push('\n} as const;\n');
  parts.push(FOOTER);
  return parts.join('');
}
