// Every calibration constant in the game lives here (CLAUDE.md rule 10).
// A band with verified: true was computed by scripts/calibrate.ts from FDIC
// data and carries the query, window, and date. A band with verified: false
// was typed by hand and says why. Tests that read an unverified band are
// tagged unverified and report separately (rule 20). Never tune a band to
// make a test pass.
//
// Generated by scripts/calibrate.ts. Edit hand-entered bands here; computed
// bands are overwritten on the next run.

export interface Band {
  low: number;
  high: number;
  typical: number;
  unit: string;
  source: string;
  verified: boolean;
  note: string;
  query?: string;
  window?: string;
  computedOn?: string;
}

const UNVERIFIED =
  'Hand-entered from memory of FDIC Quarterly Banking Profile ranges. Not computed. scripts/calibrate.ts replaces this once the FDIC API is reachable.';

export const calibration = {
  // Annual net charge-off rate by loan type, percent of average loans,
  // across a full cycle. FDIC RI-B and RC-N.
  chargeOffRate: {
    ci: { low: 0.199, high: 1.7849, typical: 0.4836, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly net charge-offs divided by year-end loan balance, all insured institutions; 5th, 50th, 95th percentile of the yearly values.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NTCI,LNCI', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    cre_oo: { low: 0.0193, high: 0.7321, typical: 0.0777, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly net charge-offs divided by year-end loan balance, all insured institutions; 5th, 50th, 95th percentile of the yearly values.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NTRENROW,LNRENROW', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    cre_inv: { low: 0.0238, high: 0.9918, typical: 0.1569, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly net charge-offs divided by year-end loan balance, all insured institutions; 5th, 50th, 95th percentile of the yearly values.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NTRENROT,LNRENROT', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    construction: { low: -0.0253, high: 5.5168, typical: 0.053, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly net charge-offs divided by year-end loan balance, all insured institutions; 5th, 50th, 95th percentile of the yearly values.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NTRECONS,LNRECONS', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    resi: { low: -0.019, high: 1.7709, typical: 0.0973, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly net charge-offs divided by year-end loan balance, all insured institutions; 5th, 50th, 95th percentile of the yearly values.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NTRERES,LNRERES', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    consumer: { low: 1.3541, high: 4.9325, typical: 2.3201, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly net charge-offs divided by year-end loan balance, all insured institutions; 5th, 50th, 95th percentile of the yearly values.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NTCON,LNCON', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    ag: { low: 0.02, high: 2, typical: 0.15, unit: 'percent per year', source: 'FDIC QBP, RI-B agriculture', verified: false, note: UNVERIFIED },
    energy: { low: 0.1, high: 8, typical: 1, unit: 'percent per year', source: 'FDIC QBP, RI-B C&I (oil and gas subset)', verified: false, note: UNVERIFIED },
    cards: { low: 2, high: 11, typical: 3.5, unit: 'percent per year', source: 'FDIC QBP, RI-B credit cards', verified: false, note: UNVERIFIED },
  },
  dealPriceToBook: {
    expansion: { low: 120, high: 200, typical: 150, unit: 'percent of tangible book', source: 'S&P Global bank M&A, 2010 to 2023', verified: false, note: UNVERIFIED },
    recession: { low: 60, high: 120, typical: 85, unit: 'percent of tangible book', source: 'S&P Global bank M&A, 2008 to 2010', verified: false, note: UNVERIFIED },
  },
  assistedDepositPremium: { low: 0, high: 5, typical: 1, unit: 'percent of deposits assumed', source: 'FDIC purchase and assumption results, 2008 to 2023', verified: false, note: UNVERIFIED },
  acquiredDepositAttrition: { low: 3, high: 20, typical: 8, unit: 'percent of acquired deposits in the first year', source: 'Bank M&A studies, deposit runoff after closing', verified: false, note: UNVERIFIED },
  integrationCost: { low: 1, high: 4, typical: 2, unit: 'percent of target assets, one time', source: 'Bank merger announcements, one time merger charges', verified: false, note: UNVERIFIED },
  mortgageGainOnSale: { low: 100, high: 300, typical: 180, unit: 'basis points of volume', source: 'MBA quarterly mortgage banking profitability', verified: false, note: UNVERIFIED },
  cardInterchange: { low: 150, high: 300, typical: 220, unit: 'basis points of purchase volume', source: 'Fed interchange fee studies, credit cards', verified: false, note: UNVERIFIED },
  wealthFeeRate: { low: 50, high: 100, typical: 70, unit: 'basis points of AUM per year', source: 'Wealth management fee surveys', verified: false, note: UNVERIFIED },
  ibFeeToAssets: { low: 2, high: 10, typical: 5, unit: 'basis points of assets per year', source: 'Investment banking fees at universal banks vs assets', verified: false, note: UNVERIFIED },
  bankPriceToBook: {
    expansion: { low: 110, high: 220, typical: 150, unit: 'percent of tangible book', source: 'KBW bank index price to tangible book, 2010 onward', verified: false, note: UNVERIFIED },
    recession: { low: 50, high: 110, typical: 80, unit: 'percent of tangible book', source: 'KBW bank index price to tangible book, 2008 to 2009, 2020, 2023', verified: false, note: UNVERIFIED },
  },
  costOfEquity: { low: 8, high: 13, typical: 10, unit: 'percent per year', source: 'Bank cost of equity estimates, CAPM', verified: false, note: UNVERIFIED },
  // Return on average assets by asset size bucket, percent per year.
  roa: {
    under1b: { low: 0.252, high: 1.247, typical: 1.0729, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly net income over year-end assets, institutions under $1B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NETINC,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    from1bTo10b: { low: -0.1312, high: 1.3419, typical: 1.1223, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly net income over year-end assets, institutions $1B to $10B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NETINC,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    from10bTo250b: { low: -0.0045, high: 1.4287, typical: 1.0885, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly net income over year-end assets, institutions $10B to $250B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NETINC,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    over250b: { low: 0.4899, high: 1.215, typical: 1.018, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly net income over year-end assets, institutions over $250B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NETINC,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
  },
  // Net interest margin by size bucket, percent per year.
  nim: {
    under1b: { low: 3.4178, high: 4.1623, typical: 3.735, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: asset weighted mean of reported net interest margin, institutions under $1B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NIMY,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    from1bTo10b: { low: 3.3546, high: 3.9241, typical: 3.6439, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: asset weighted mean of reported net interest margin, institutions $1B to $10B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NIMY,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    from10bTo250b: { low: 3.2385, high: 3.965, typical: 3.6121, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: asset weighted mean of reported net interest margin, institutions $10B to $250B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NIMY,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    over250b: { low: 2.4125, high: 3.4247, typical: 2.9751, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: asset weighted mean of reported net interest margin, institutions over $250B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NIMY,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
  },
  // Deposit beta: change in cost of interest-bearing deposits per change in
  // Fed funds over a hiking cycle.
  depositBeta: {
    checking: { low: 0, high: 0.1, typical: 0.05, unit: 'ratio', source: 'FDIC QBP cost of funds vs FEDFUNDS; 2022 to 2024 cycle betas at community banks', verified: false, note: UNVERIFIED },
    savings: { low: 0.1, high: 0.4, typical: 0.25, unit: 'ratio', source: 'FDIC QBP cost of funds vs FEDFUNDS; 2022 to 2024 cycle betas at community banks', verified: false, note: UNVERIFIED },
    mmda: { low: 0.3, high: 0.7, typical: 0.55, unit: 'ratio', source: 'FDIC QBP cost of funds vs FEDFUNDS; 2022 to 2024 cycle betas at community banks', verified: false, note: UNVERIFIED },
    cd: { low: 0.5, high: 0.9, typical: 0.8, unit: 'ratio', source: 'FDIC QBP cost of funds vs FEDFUNDS; 2022 to 2024 cycle betas at community banks', verified: false, note: UNVERIFIED },
    brokered: { low: 0.85, high: 1.05, typical: 0.95, unit: 'ratio', source: 'FDIC QBP cost of funds vs FEDFUNDS', verified: false, note: UNVERIFIED },
    aggregate: { low: 0.3671, high: 0.4709, typical: 0.4511, unit: 'ratio', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions; FRED FEDFUNDS annual average', verified: true, note: 'Computed by scripts/calibrate.ts: (change in interest expense on deposits / interest-bearing deposits) / (change in average Fed funds) over hiking cycles 2004-2006, 2015-2019, 2021-2023. Per-type betas stay hand-entered.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=EDEP,DEPI', window: '2004-2006, 2015-2019, 2021-2023', computedOn: '2026-09-28' },
  },
  // Noninterest expense to average assets, percent per year.
  nieToAssets: {
    under1b: { low: 2.9634, high: 3.3604, typical: 3.2343, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly noninterest expense over year-end assets, institutions under $1B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NONIX,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    from1bTo10b: { low: 2.5327, high: 3.0935, typical: 2.8123, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly noninterest expense over year-end assets, institutions $1B to $10B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NONIX,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    from10bTo250b: { low: 2.3209, high: 3.343, typical: 2.8407, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly noninterest expense over year-end assets, institutions $10B to $250B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NONIX,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
    over250b: { low: 2.0936, high: 3.0853, typical: 2.617, unit: 'percent per year', source: 'FDIC BankFind financials API, year-end call reports, all insured institutions', verified: true, note: 'Computed by scripts/calibrate.ts: yearly noninterest expense over year-end assets, institutions over $250B.', query: 'https://api.fdic.gov/banks/financials?filters=REPDTE:YYYY1231 AND <asset bucket>&fields=NONIX,ASSET', window: '2000-12-31 to 2025-12-31, year-end call reports', computedOn: '2026-09-28' },
  },
  // Bank failures per year across the cycle, count, 2000 onward.
  failuresPerYear: {
    normal: { low: 0, high: 24, typical: 4, unit: 'banks per year', source: 'FDIC failures API (failed bank list)', verified: true, note: 'Computed by scripts/calibrate.ts: normal years are 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025; low and high are the min and max count, typical the median. A crisis year has at least 25 failures.', query: 'https://api.fdic.gov/banks/failures?filters=FAILYR%3A%5B2000%20TO%202025%5D&fields=FAILYR&limit=10000&format=json', window: '2000 to 2025', computedOn: '2026-09-28' },
    crisis: { low: 30, high: 157, typical: 92, unit: 'banks per year', source: 'FDIC failures API (failed bank list)', verified: true, note: 'Computed by scripts/calibrate.ts: crisis years are 2008, 2009, 2010, 2011, 2012; low and high are the min and max count, typical the median. A crisis year has at least 25 failures.', query: 'https://api.fdic.gov/banks/failures?filters=FAILYR%3A%5B2000%20TO%202025%5D&fields=FAILYR&limit=10000&format=json', window: '2000 to 2025', computedOn: '2026-09-28' },
  },
  effectiveTaxRate: { low: 21, high: 28, typical: 25, unit: 'percent of pretax income', source: 'IRC section 11 (21% federal) plus state bank taxes', verified: false, note: UNVERIFIED },
  fdicAssessment: { low: 3, high: 30, typical: 5, unit: 'basis points of assets less tangible equity per year', source: 'FDIC assessment rate schedule 12 CFR 327', verified: false, note: UNVERIFIED },
  salariesShareOfNie: { low: 45, high: 62, typical: 55, unit: 'percent of noninterest expense', source: 'FDIC QBP, salaries and benefits vs total NIE', verified: false, note: UNVERIFIED },
  occupancyShareOfNie: { low: 8, high: 16, typical: 12, unit: 'percent of noninterest expense', source: 'FDIC QBP, premises expense vs total NIE', verified: false, note: UNVERIFIED },
  cashYieldVsFedFunds: { low: -15, high: 15, typical: 7, unit: 'basis points', source: 'Fed IORB minus effective fed funds, 2022 onward', verified: false, note: UNVERIFIED },
  serviceChargeRate: { low: 0.15, high: 0.5, typical: 0.3, unit: 'percent of core deposits per year', source: 'FDIC QBP service charges on deposit accounts vs domestic deposits, community banks', verified: false, note: UNVERIFIED },
  interchangeRate: { low: 0.3, high: 1, typical: 0.6, unit: 'percent of checking balances per year', source: 'Fed debit card interchange revenue vs transaction account balances', verified: false, note: UNVERIFIED },
  loanFeeRate: { low: 0.05, high: 0.3, typical: 0.15, unit: 'percent of loans per year', source: 'FDIC QBP other noninterest income (loan and servicing fees) vs loans, community banks', verified: false, note: UNVERIFIED },
  loanSpreadOverFedFunds: { low: 150, high: 350, typical: 250, unit: 'basis points', source: 'FDIC QBP loan yield vs FEDFUNDS, community banks', verified: false, note: UNVERIFIED },
  rivalDividendPayout: { low: 20, high: 50, typical: 35, unit: 'percent of quarterly earnings', source: 'FDIC QBP dividends vs net income', verified: false, note: UNVERIFIED },
  rivalLeverageTarget: { low: 6.5, high: 11, typical: 9, unit: 'percent of assets before a 1.5 point buffer, thinner with risk appetite', source: 'FDIC QBP community bank leverage ratios: median near 10.5, tenth percentile near 8.5; the banks that failed in 2008 to 2010 ran 6 to 8 before their losses', verified: false, note: UNVERIFIED },
  rivalSecuritiesShare: { low: 12, high: 28, typical: 20, unit: 'percent of assets, lower with risk appetite', source: 'FDIC QBP securities to assets at community banks', verified: false, note: UNVERIFIED },
  ceoSalaryPerBillionAssets: { low: 150, high: 400, typical: 250, unit: 'thousands of dollars per year at $1B assets, log scaled', source: 'Bank CEO pay surveys, community banks', verified: false, note: UNVERIFIED },
  founderCash: { low: 2, high: 10, typical: 5, unit: 'millions of dollars', source: 'Design choice, no public source: what a de novo organizer group member typically commits', verified: false, note: UNVERIFIED },
  depositRateElasticity: { low: 3, high: 15, typical: 8, unit: 'percent change in deposit share per 100bp above market', source: 'Fed and FDIC deposit competition studies, community banks', verified: false, note: UNVERIFIED },
  depositsToPersonalIncome: { low: 0.6, high: 1, typical: 0.75, unit: 'ratio', source: 'FDIC QBP domestic deposits (about 17.5 trillion) over BEA personal income (about 24 trillion), 2024, from memory', verified: false, note: UNVERIFIED },
  banksPerMillionPeople: { low: 8, high: 20, typical: 13.5, unit: 'banks per million residents', source: 'FDIC: about 4,500 insured institutions for 335 million people, 2024, from memory', verified: false, note: UNVERIFIED },
  bankSizeSpread: { low: 1.4, high: 2.2, typical: 1.8, unit: 'log standard deviation of assets', source: 'FDIC size distribution: median institution near 350 million of assets, mean near 5 billion, from memory', verified: false, note: UNVERIFIED },
  largestBankAssets: { low: 3, high: 3.6, typical: 3.4, unit: 'trillions of dollars', source: 'largest US bank by assets, 2024, from memory', verified: false, note: UNVERIFIED },
  nationalRankDecay: { low: 0.6, high: 1, typical: 0.8, unit: 'exponent', source: 'assets of the largest banks fall roughly as rank to the minus 0.8 (3.4T, 2.5T, 1.8T, 1.7T, then a gap), from memory', verified: false, note: UNVERIFIED },
  bankDepositsToAssets: { low: 0.75, high: 0.9, typical: 0.82, unit: 'ratio', source: 'FDIC QBP domestic deposits over total assets, all insured institutions, 2024, from memory', verified: false, note: UNVERIFIED },
  startFedFunds: { low: 4.3, high: 4.6, typical: 4.48, unit: 'percent', source: 'FRED FEDFUNDS, December 2024 monthly average, from memory', verified: false, note: UNVERIFIED },
  startDgs3mo: { low: 4.2, high: 4.5, typical: 4.37, unit: 'percent', source: 'FRED DGS3MO, end of December 2024, from memory', verified: false, note: UNVERIFIED },
  startDgs2: { low: 4.1, high: 4.4, typical: 4.25, unit: 'percent', source: 'FRED DGS2, end of December 2024, from memory', verified: false, note: UNVERIFIED },
  startDgs30: { low: 4.6, high: 4.9, typical: 4.78, unit: 'percent', source: 'FRED DGS30, end of December 2024, from memory', verified: false, note: UNVERIFIED },
  loanRateElasticity: { low: 4, high: 15, typical: 8, unit: 'percent more applications per 25bp under market', source: 'No public series. Set on the scale of the deposit band; a hand band until a source exists', verified: false, note: UNVERIFIED },
  depositsPerBranch: { low: 9.4, high: 365.9, typical: 77.3, unit: 'millions of dollars per branch', source: 'FDIC Summary of Deposits 2024, branch level (raw/fdic_sod_2024.json)', verified: true, note: 'Computed by scripts/calibrate.ts: 5th, 50th and 95th percentile of deposits per office across 69923 branch offices (main offices excluded).', query: 'https://api.fdic.gov/banks/sod?filters=YEAR:2024&fields=STCNTYBR,DEPSUMBR,BRNUM,CERT', window: 'June 30, 2024', computedOn: '2026-09-28' },
  deNovoShareCeiling: { low: 1, high: 5, typical: 2.5, unit: 'percent of home county deposits after ramp', source: 'FDIC de novo studies, share after 5 years', verified: false, note: UNVERIFIED },
  branchReachKm: { low: 150, high: 800, typical: 400, unit: 'km from home at which a branch of a $100M bank gathers a third of what it would at home; reach grows with the fourth root of assets', source: 'no public study found; community bank branch networks are regional, national banks reach everywhere', verified: false, note: UNVERIFIED },
  tdrRedefaultRate: { low: 20, high: 50, typical: 35, unit: 'percent of restructured loans 60 or more days late again within a year', source: 'OCC Mortgage Metrics Report, modified loans re-defaulting within twelve months, 2012 to 2019', verified: false, note: UNVERIFIED },
  operatingBalanceShare: { low: 5, high: 20, typical: 10, unit: 'percent of C&I and owner occupied CRE balances the borrowers keep on deposit with the lender', source: 'compensating balance practice; Federal Reserve Senior Loan Officer Opinion Survey on business deposit relationships', verified: false, note: UNVERIFIED },
  branchDepositPremium: { low: 2, high: 8, typical: 4, unit: 'percent of deposits assumed in a branch purchase', source: 'S&P Global Market Intelligence, US branch deal deposit premiums 2015 to 2023', verified: false, note: UNVERIFIED },
  largeDepositPremium: { low: 25, high: 100, typical: 50, unit: 'basis points over the market rate on a negotiated business or public deposit', source: 'public funds and corporate treasury deposit pricing practice; FDIC national rate cap methodology', verified: false, note: UNVERIFIED },
  branchOverCapacityGrowth: { low: 0.5, high: 2, typical: 1, unit: 'percent a month a branch past its capacity can still add toward its share of the county', source: 'FDIC Summary of Deposits: single office banks over $1B are rare outliers; branch deposit growth past maturity runs a few percent a year', verified: false, note: UNVERIFIED },
  officerSearchDays: { low: 60, high: 180, typical: 90, unit: 'days from a senior officer leaving to an interim or permanent replacement in the seat', source: 'executive search practice; community banks name an interim officer at once and fill the seat within one to six months', verified: false, note: UNVERIFIED },
  takeoverPremium: { low: 100, high: 160, typical: 125, unit: 'percent of book value for a control stake', source: 'S&P bank M&A price to tangible book, small deals', verified: false, note: UNVERIFIED },
  countries: {
    GB: {
      fx: { low: 0.7, high: 0.9, typical: 0.79, unit: 'GBP per USD', source: 'FRED DEXUSUK inverted, 2024', verified: false, note: UNVERIFIED },
      rate: { low: 3, high: 6, typical: 5.25, unit: 'percent', source: 'Bank of England bank rate, 2024', verified: false, note: UNVERIFIED },
      deposits: { low: 2500, high: 3500, typical: 3000, unit: 'billions USD', source: 'BIS and BoE monetary statistics, sterling deposits', verified: false, note: UNVERIFIED },
      leverageMin: { low: 3, high: 4, typical: 3.25, unit: 'percent', source: 'PRA leverage ratio minimum', verified: false, note: UNVERIFIED },
      sovereignSpread: { low: 0, high: 50, typical: 10, unit: 'basis points over US', source: 'gilt spreads', verified: false, note: UNVERIFIED },
      beta: { low: 50, high: 90, typical: 70, unit: 'percent of US cycle', source: 'OECD business cycle correlation UK to US', verified: false, note: UNVERIFIED },
    },
    JP: {
      fx: { low: 120, high: 170, typical: 150, unit: 'JPY per USD', source: 'FRED DEXJPUS, 2024', verified: false, note: UNVERIFIED },
      rate: { low: -0.1, high: 1, typical: 0.1, unit: 'percent', source: 'Bank of Japan policy rate, 2024', verified: false, note: UNVERIFIED },
      deposits: { low: 8000, high: 11000, typical: 9500, unit: 'billions USD', source: 'BoJ deposits at domestically licensed banks', verified: false, note: UNVERIFIED },
      leverageMin: { low: 3, high: 4, typical: 3, unit: 'percent', source: 'FSA leverage ratio', verified: false, note: UNVERIFIED },
      sovereignSpread: { low: -100, high: 50, typical: -30, unit: 'basis points over US', source: 'JGB yields', verified: false, note: UNVERIFIED },
      beta: { low: 30, high: 70, typical: 50, unit: 'percent of US cycle', source: 'OECD business cycle correlation Japan to US', verified: false, note: UNVERIFIED },
    },
    DE: {
      fx: { low: 0.85, high: 1, typical: 0.92, unit: 'EUR per USD', source: 'FRED DEXUSEU inverted, 2024', verified: false, note: UNVERIFIED },
      rate: { low: 2, high: 4.5, typical: 4, unit: 'percent', source: 'ECB deposit facility rate, 2024', verified: false, note: UNVERIFIED },
      deposits: { low: 3500, high: 4500, typical: 4000, unit: 'billions USD', source: 'Bundesbank deposits of non banks', verified: false, note: UNVERIFIED },
      leverageMin: { low: 3, high: 3.5, typical: 3, unit: 'percent', source: 'CRR leverage ratio', verified: false, note: UNVERIFIED },
      sovereignSpread: { low: -150, high: 0, typical: -100, unit: 'basis points over US', source: 'Bund yields', verified: false, note: UNVERIFIED },
      beta: { low: 50, high: 90, typical: 70, unit: 'percent of US cycle', source: 'OECD business cycle correlation Germany to US', verified: false, note: UNVERIFIED },
    },
    HK: {
      fx: { low: 7.75, high: 7.85, typical: 7.8, unit: 'HKD per USD', source: 'FRED DEXHKUS, peg band', verified: false, note: UNVERIFIED },
      rate: { low: 3, high: 6, typical: 5.75, unit: 'percent', source: 'HKMA base rate, 2024', verified: false, note: UNVERIFIED },
      deposits: { low: 1800, high: 2400, typical: 2100, unit: 'billions USD', source: 'HKMA total deposits', verified: false, note: UNVERIFIED },
      leverageMin: { low: 3, high: 3.5, typical: 3, unit: 'percent', source: 'HKMA Basel III leverage', verified: false, note: UNVERIFIED },
      sovereignSpread: { low: 0, high: 100, typical: 30, unit: 'basis points over US', source: 'HK government bond yields', verified: false, note: UNVERIFIED },
      beta: { low: 40, high: 90, typical: 65, unit: 'percent of US cycle', source: 'HK exposure to the global cycle and China', verified: false, note: UNVERIFIED },
    },
  },
  sovereignEventPerYear: { low: 0.2, high: 2, typical: 0.5, unit: 'percent chance per country per year', source: 'Reinhart and Rogoff sovereign crisis frequency, advanced economies', verified: false, note: UNVERIFIED },
  fxVolatility: { low: 6, high: 12, typical: 8, unit: 'percent per year', source: 'FRED major currency realized volatility', verified: false, note: UNVERIFIED },
  // Economy. These are not FDIC bands and stay hand-entered with sources.
  recessionIntervalYears: { low: 7, high: 12, typical: 9, unit: 'years', source: 'NBER business cycle dates, 1970 onward', verified: false, note: UNVERIFIED },
  bankingCrisisShare: { low: 0.25, high: 0.45, typical: 0.33, unit: 'fraction of recessions', source: 'NBER dates vs FDIC failure waves (S&L, 2008)', verified: false, note: UNVERIFIED },
  energyDrawdownPer15y: { low: 1, high: 3, typical: 1.5, unit: 'drawdowns of 50% or more', source: 'FRED DCOILWTICO 1986 onward', verified: false, note: UNVERIFIED },
  // Deposits. Fed +400bp shock outcomes, from 2022 to 2023 experience.
  shockOutflow: { low: 2, high: 15, typical: 6, unit: 'percent of deposits over 12 months', source: 'Fed H.8 2022 to 2023', verified: false, note: UNVERIFIED },
  shockUnrealizedLoss: { low: 5, high: 40, typical: 15, unit: 'percent of equity', source: 'FDIC QBP unrealized losses 2022 to 2023', verified: false, note: UNVERIFIED },
  mainOfficeMultiple: { low: 0.92, high: 3.42, typical: 1.74, unit: 'main office deposits over the median branch office', source: 'FDIC Summary of Deposits 2024, branch level (raw/fdic_sod_2024.json)', verified: true, note: 'Computed by scripts/calibrate.ts: the 25th, 50th and 75th percentile of deposits at 4477 main offices divided by the median branch office.', query: 'https://api.fdic.gov/banks/sod?filters=YEAR:2024&fields=STCNTYBR,DEPSUMBR,BRNUM,CERT', window: 'June 30, 2024', computedOn: '2026-09-28' },
} as const;

export type Calibration = typeof calibration;

export function unverifiedBands(): string[] {
  const out: string[] = [];
  const walk = (node: unknown, path: string) => {
    if (node && typeof node === 'object') {
      if ('verified' in node && 'low' in node) {
        if (!(node as Band).verified) out.push(path);
        return;
      }
      for (const [k, v] of Object.entries(node)) walk(v, path ? `${path}.${k}` : k);
    }
  };
  walk(calibration, '');
  return out;
}
