// Plain words for bank words. Every term on the desk that a player might
// not know gets one sentence here, shown on hover. Real definitions,
// stated the way a banker would explain them to a new director.

export const TERMS: Record<string, string> = {
  assets: 'Everything the bank owns: cash, bonds, loans, buildings.',
  liabilities: 'Everything the bank owes: deposits and borrowings.',
  equity: 'What is left for shareholders after the debts. This is the capital.',
  'leverage ratio': 'Capital as a share of everything the bank owns. Below 5% the regulators step in; below 2% they close the bank.',
  'well capitalized': 'Leverage of 5% or more and the risk-based ratios above their minimums: the top regulatory category, and the one that lets you pay dividends and buy brokered deposits.',
  'tier 1 capital': 'The strongest capital: common stock plus retained earnings, less goodwill.',
  CET1: 'Common equity tier 1: the core capital ratio, measured against risk-weighted assets. Minimum 4.5% plus a 2.5% buffer before payouts are limited.',
  'risk-weighted assets': 'Assets scaled by how risky they are. Cash counts for nothing; a construction loan counts in full.',
  allowance: 'Money set aside against loans that will not be repaid. Losses come out of it; provisions top it up.',
  provision: 'The charge to earnings that keeps the allowance large enough for the losses expected in the book.',
  'charge-off': 'A loan written off as lost. Anything collected later comes back as a recovery.',
  criticized: 'Loans the bank itself has graded as weak: the watch list and worse, grades 6 to 9.',
  nonaccrual: 'Loans so far behind that their interest no longer counts as income: grades 7 to 9.',
  grade: 'The bank’s own 1 to 9 quality rating for a loan. 1 is the safest; 6 and up are criticized; 9 is a loss.',
  coverage: 'Debt service coverage: cash flow divided by loan payments. Above 1.25x is comfortable; below 1.0x the borrower cannot pay from income.',
  'loan to value': 'The loan as a share of what the collateral is worth. Lower is safer for the bank.',
  'C&I': 'Commercial and industrial loans: money lent to businesses for operations and equipment.',
  'CRE owner occupied': 'A loan on a building the borrower uses for its own business.',
  'CRE investor': 'A loan on a building rented out to others. Riskier, because it depends on tenants.',
  Construction: 'Loans to build. The riskiest book: nothing earns until the project is finished and sold or leased.',
  '1-4 family': 'Home mortgages on houses of one to four units.',
  Consumer: 'Car loans, personal loans and other lending to households.',
  Agriculture: 'Loans to farms and ranches, tied to crop prices and land values.',
  'Oil and gas': 'Loans to energy producers, secured by reserves and tied to the oil price.',
  'Credit cards': 'Card balances: high yield, high losses, and they leave fast in a downturn.',
  yield: 'The interest rate the book earns on average.',
  'net interest margin': 'What the bank earns on its money after paying for it, as a share of assets. Most of a bank’s profit lives here.',
  'return on assets': 'Profit as a share of everything the bank owns. A good year is about 1%.',
  'net charge-offs': 'Loans written off, less recoveries, as a share of the book per year.',
  Checking: 'Everyday accounts. Cheap money that stays and pays almost no interest.',
  Savings: 'Savings accounts. Sticky and cheap.',
  'Money market': 'Higher-rate accounts. Money that leaves quickly when your rate falls behind.',
  Certificates: 'Certificates of deposit: fixed term, fixed rate, held by rate shoppers.',
  Brokered: 'Deposits bought through brokers at market rates. Fast to raise, fast to leave, and only for well capitalized banks.',
  uninsured: 'Deposits above the $250,000 insurance limit. The first money to run when confidence slips.',
  'depositor confidence': 'How safe depositors believe the bank is. It falls with thin capital, unrealized losses on bonds, and failures nearby.',
  'FHLB advances': 'Loans from the Federal Home Loan Bank, secured by your mortgages. A standing line of credit for any member bank.',
  'fed funds purchased': 'Overnight borrowing from other banks, arranged automatically when cash runs short.',
  'subordinated debt': 'Long-term borrowing that ranks behind deposits if the bank fails. It counts as tier 2 capital.',
  'available for sale': 'Bonds you can sell at any time. Marked to market every month; the swings hit equity through AOCI, not earnings.',
  'held to maturity': 'Bonds you have promised to keep. Carried at cost, so no market swings, but they cannot be sold.',
  AOCI: 'Accumulated other comprehensive income: unrealized gains and losses on bonds and hedges, parked in equity and left out of tier 1 capital.',
  'unrealized loss': 'How far your bonds are under water at today’s rates. It becomes real only if you sell.',
  duration: 'How sensitive a bond is to rates. A five year duration loses about 5% of its value for every one point rise in rates.',
  Treasury: 'Bonds issued by the US government. The safest, with the lowest yield.',
  Agency: 'Bonds issued by Fannie Mae, Freddie Mac and the Home Loan Banks. Nearly as safe, slightly higher yield.',
  'Agency MBS': 'Mortgage-backed securities guaranteed by the agencies. Higher yield, but they pay off faster when rates fall and slower when they rise.',
  swaps: 'Interest rate swaps: pay a fixed rate, receive a floating one, to offset losses on your bonds when rates rise.',
  CAMELS: 'The examiner’s rating from 1 (strong) to 5 (failing) across Capital, Assets, Management, Earnings, Liquidity and Sensitivity.',
  'memorandum of understanding': 'An informal agreement with the regulator to fix the listed problems by the next exam.',
  'consent order': 'A formal enforcement order: no growth, no dividends and no brokered deposits until the findings are fixed.',
  'prompt corrective action': 'The directive an undercapitalized bank receives, with a 90 day clock to recapitalize or be closed.',
  'FDIC assessment': 'The deposit insurance premium: a few basis points of assets a year, more for riskier banks.',
  'holding company': 'A parent company above the bank. Needed to sell stock to the public, borrow at the parent, and pay for other banks with stock.',
  'book value': 'Equity divided by shares: what each share is worth on paper.',
  'price to book': 'What a buyer pays relative to book value. Banks change hands near 1.5x in good times and below 1x in bad ones.',
  goodwill: 'The premium paid over book value in an acquisition. It sits on the balance sheet but counts for nothing as capital.',
  'delegation dial': 'Which loans reach your desk. Loans above the size line come to you; so do loans worse than the grade line if you set one. The rest are decided by the loan officer under your written policy.',
  'loan policy': 'Your written rules: minimum coverage, maximum leverage, maximum loan size, maximum loan to value by type, and which types you make at all.',
  'sector concentration': 'How much of the book sits in one industry. Concentrated books move together in a bust.',
  'CRE concentration': 'Construction above 100% of capital, or investor real estate above 300%, draws an automatic examiner finding.',
  'stress test': 'From $100B of assets, a yearly test of whether capital survives a severe recession. Failing it stops dividends for a year.',
  'call report': 'The quarterly financial report every bank files with the FDIC.',
  'fed funds rate': 'The Federal Reserve’s policy rate. Deposit costs and loan yields follow it.',
  cycle: 'Where the economy is: expansion, late cycle, recession or recovery. About one recession in three is a banking crisis.',
  'banking crisis': 'A recession where the losses land on the banks: many failures, cheap deals, and runs on the weak.',
  'net worth': 'Your own cash plus your shares at book value, or at the market price once the bank is public. This is the score.',
  dividends: 'The share of each quarter’s profit paid out to shareholders, you included. Every dollar paid out is a dollar less capital.',
  'gain on sale': 'The profit from originating a mortgage and selling it to Fannie Mae or Freddie Mac instead of holding it.',
  interchange: 'The fee a card issuer earns on every purchase.',
  'basis point': 'One hundredth of a percent. Twenty five basis points is a quarter of a percent.',
  'loss environment': 'How much worse than a normal year loans of this type are going bad right now, from unemployment, home prices, the sector and your county. 1x is normal; 2x is a bad year; the 2009 peak was 4x to 25x depending on the type.',
  'expected loss': 'What the loans you hold in this type should lose over the next year at today\'s stress: the chance each grade defaults, times what a default costs.',
  'margin after losses': 'The market rate less what your deposits cost less the expected loss. What is left pays the running costs and the shareholders.',
  'inverted curve': 'Short rates above long rates. Banks borrow short and lend long, so an inverted curve squeezes margins, and a recession has followed every one within two years.',
  'cost of money': 'The average rate you pay on deposits and borrowings. Every loan has to earn more than this plus its losses.',
  'loan committee': 'The officers who decide the larger credits together under the written policy. With the committee deciding, the sound loans (health 65 and up, within policy) are made without you and the rest declined; you see only the biggest.',
  'note sale': 'Selling a troubled loan to a buyer who specializes in collecting them, for less than is owed. The bank gets cash now and writes off the difference today instead of waiting through a workout.',
  REO: 'Real estate owned: property the bank took back in a foreclosure, carried at what it should sell for. It sells over the following months, or sooner at a discount.',
  'investment policy': 'The board\'s standing order for idle cash: how much to keep as cash, what bonds to buy with the rest, how long, and whether they can be sold. The CFO executes it at each month end.',
  'loans to deposits': 'Loans as a share of deposits. A community bank runs at 70% to 90%; above 100% the loans are funded with borrowed money.',
  'Return on assets': 'Profit as a share of everything the bank owns, annualized from the last quarter. A good year is about 1%.',
  'Net interest margin': 'What the bank earns on its money after paying for it, as a share of assets. Most of a bank’s profit lives here.',
  'Costs as a share of revenue': 'Salaries, buildings and the rest, divided by what the bank earns before those costs. Bankers call it the efficiency ratio; under 60% is good.',
  'Loans lost a year': 'Net charge-offs as a share of loans, annualized. Half a percent is normal for a community bank; two percent is a bad year.',
  'Cost of deposits': 'Interest paid to depositors as a share of deposits, annualized. Checking is free money; certificates are not.',
  'Loans to deposits': 'Loans as a share of deposits. A community bank runs at 70% to 90%; above 100% the loans are funded with borrowed money.',
  'Growth over a year': 'Assets today against a year ago. Faster than the economy means you are taking share or taking risk.',
  'Capital (leverage ratio)': 'Capital as a share of everything the bank owns. Below 5% the regulators step in; below 2% they close the bank.',
  'restructure': 'New terms for a borrower who cannot pay the old ones: a lower rate, a longer term, a smaller payment. The loan stays on nonaccrual until six clean payments.',
  'follows the market': 'Your deposit rates are reset every month to the market rate plus the offset you chose, the way a real bank reprices at its ALCO meeting.',
  'loan health': 'A credit committee\'s read of the memo, 0 to 100: capacity to pay, collateral cushion, character, the borrower\'s own capital, conditions in the type and sector, and concentration. Computed only from what is on the memo.',
  'lending limit': 'The legal limit on loans to one borrower: 15% of capital for a national bank. Above it the loan is not allowed at all; near it one bad name can take a year of earnings.',
  'five Cs': 'What every lender has looked at since there were lenders: capacity, capital, collateral, character and conditions.',
};
